# Use the official php:apache image as a base
FROM php:apache

# Install mysqli extension
RUN docker-php-ext-install mysqli

RUN apt-get update -y && apt-get install -y sendmail libpng-dev

RUN apt-get update && \
    apt-get install -y \
        zlib1g-dev

        
RUN docker-php-ext-install gd
